from __future__ import annotations

import json
from pathlib import Path
from typing import Literal

Lang = Literal["python", "node", "rust"]


NODE_SERVER = r"""/*
Generated by Capax.
Minimal Node.js HTTP server that enforces the compiled policy in-memory.
No frameworks. No database. Just capacity math.
*/
const http = require("http");
const fs = require("fs");
const crypto = require("crypto");

function nowMs(){ return Date.now(); }

function stableJson(obj){
  const keys = Object.keys(obj || {}).sort();
  const out = {};
  for (const k of keys) out[k] = obj[k];
  return JSON.stringify(out);
}

function sha256Hex(str){
  return crypto.createHash("sha256").update(str, "utf8").digest("hex");
}

function splitTokens(raw, seps){
  let tokens = [raw];
  for (const sep of seps){
    const next = [];
    for (const t of tokens){
      if (t.includes(sep)){
        for (const part of t.split(sep)){
          const s = (part || "").trim();
          if (s) next.push(s);
        }
      } else {
        next.push((t || "").trim());
      }
    }
    tokens = next;
  }
  const seen = new Set();
  const out = [];
  for (const t of tokens){
    if (!seen.has(t)){ out.push(t); seen.add(t); }
  }
  return out;
}

function computeCost(policy, body){
  const field = policy.cost_expression.field;
  if (!field) return {cost: 1, err: null};
  const raw = body[field];
  if (raw === undefined || raw === null) return {cost: 1, err: null};

  const tokenCosts = policy.cost_expression.token_costs || {};
  const tokenCostsCI = {};
  for (const k of Object.keys(tokenCosts)){
    tokenCostsCI[String(k).toLowerCase()] = Number(tokenCosts[k]);
  }

  const unknown = policy.cost_expression.unknown || {action:"default_cost", default_cost:1};

  function tokenCost(tok){
    if (Object.prototype.hasOwnProperty.call(tokenCosts, tok)) return {c: Number(tokenCosts[tok]), err: null};
    const k2 = String(tok).toLowerCase();
    if (Object.prototype.hasOwnProperty.call(tokenCostsCI, k2)) return {c: Number(tokenCostsCI[k2]), err: null};
    if (unknown.action === "reject_400") return {c: null, err: `unknown_token:${tok}`};
    return {c: Number(unknown.default_cost || 1), err: null};
  }

  const s = String(raw).trim();
  if (!s) return {cost: 1, err: null};

  const toks = splitTokens(s, policy.cost_expression.separators || ["|"," OR "," or "]);
  const costs = [];
  for (const t of toks){
    const {c, err} = tokenCost(t);
    if (err) return {cost: null, err};
    costs.push(Number(c));
  }
  if (!costs.length) return {cost: 1, err: null};
  if (costs.length === 1) return {cost: costs[0], err: null};
  if (policy.cost_expression.combine_mode === "bundle_sum"){
    return {cost: costs.reduce((a,b)=>a+b,0), err: null};
  }
  return {cost: Math.max(...costs), err: null};
}

function makeCapax(policy){
  const state = { inFlightCost: 0, inFlight: new Map(), served: [], uniqueCustomers: new Set() };

  function admit(method, path, body){
    const {cost, err} = computeCost(policy, body);
    if (err) return {status: 400, payload: {result:"rejected", reason: err}};
    const cap = Number(policy.capacity.max_allowed_concurrent_capacity);
    if (state.inFlightCost + Number(cost) > cap){
      return {status: Number(policy.http.codes.at_capacity), payload: {result:"rejected", reason:"at_capacity"}};
    }
    const fp = sha256Hex(`${method} ${path}\n${stableJson(body)}`);
    const orderId = fp.slice(0,12);
    state.inFlightCost += Number(cost);
    state.inFlight.set(orderId, {orderId, body, cost: Number(cost), admittedMs: nowMs()});

    setTimeout(()=> {
      const rec = state.inFlight.get(orderId);
      if (!rec) return;
      state.inFlight.delete(orderId);
      state.inFlightCost -= rec.cost;
      rec.servedMs = nowMs();
      state.served.push(rec);
      state.uniqueCustomers.add("shared");
    }, Math.max(0, Number(policy.capacity.duration_seconds) * 1000));

    return {status: Number(policy.http.codes.accepted), payload: {result:"accepted", orderId, cost: Number(cost)}};
  }

  function status(){
    return {servedOrders: state.served, uniqueCustomers: Array.from(state.uniqueCustomers)};
  }

  return {admit, status};
}

function main(){
  const policyPath = process.env.CAPAX_POLICY_PATH || "compiled_policy.json";
  const policy = JSON.parse(fs.readFileSync(policyPath, "utf8"));

  const capax = makeCapax(policy);
  const host = process.env.HOST || "127.0.0.1";
  const port = Number(process.env.PORT || 8080);

  const endpoint = policy.http.endpoint;
  const statusPath = policy.http.status_path;

  const server = http.createServer((req, res) => {
    if (req.method === "GET" && req.url === statusPath){
      res.writeHead(200, {"Content-Type":"application/json"});
      res.end(JSON.stringify(capax.status()));
      return;
    }

    if (req.method === endpoint.method && req.url === endpoint.path){
      let raw = "";
      req.on("data", chunk => { raw += chunk; });
      req.on("end", () => {
        let body = {};
        if (raw){
          try { body = JSON.parse(raw); } catch(e){ body = {}; }
        }
        if (typeof body !== "object" || body === null || Array.isArray(body)){
          res.writeHead(400, {"Content-Type":"application/json"});
          res.end(JSON.stringify({result:"rejected", reason:"body_must_be_object"}));
          return;
        }
        const out = capax.admit(endpoint.method, endpoint.path, body);
        res.writeHead(out.status, {"Content-Type":"application/json"});
        res.end(JSON.stringify(out.payload));
      });
      return;
    }

    res.writeHead(404, {"Content-Type":"application/json"});
    res.end(JSON.stringify({error:"not_found"}));
  });

  server.listen(port, host, () => {
    console.log(`Capax (node) listening on http://${host}:${port}`);
    console.log(`Endpoint: ${endpoint.method} ${endpoint.path}`);
    console.log(`Status: GET ${statusPath}`);
  });
}

main();
"""


def generate_runtime(project_root: Path, pack: str, lang: Lang) -> Path:
    out_dir = project_root / "gen" / pack / lang
    out_dir.mkdir(parents=True, exist_ok=True)

    pack_dir = project_root / "packs" / pack
    compiled = pack_dir / "compiled_policy.json"
    if not compiled.exists():
        raise FileNotFoundError(f"Missing {compiled}. Run: capax compile --pack {pack}")

    if lang == "node":
        (out_dir / "server.js").write_text(NODE_SERVER, encoding="utf-8")
        (out_dir / "package.json").write_text(json.dumps({
            "name": f"capax-{pack}-node",
            "version": "0.0.1",
            "private": True,
            "type": "commonjs",
            "scripts": {"start": "node server.js"}
        }, indent=2), encoding="utf-8")
        (out_dir / "compiled_policy.json").write_text(compiled.read_text(encoding="utf-8"), encoding="utf-8")
        return out_dir

    if lang == "python":
        (out_dir / "README.txt").write_text(
            "Python runtime uses the built-in capax server.\n"
            "Run from project root:\n"
            f"  capax run --registry server/registry.yaml --host 127.0.0.1 --port 8080\n",
            encoding="utf-8"
        )
        return out_dir

    (out_dir / "README.txt").write_text(
        "Rust runtime generation is a stub in core.\n"
        "Contract to implement from compiled_policy.json:\n"
        "- computeCost(field value, token_costs, combine_mode)\n"
        "- atomically admit if in_flight_cost + cost <= cap\n"
        "- release after duration\n"
        "- GET /status returns served orders\n",
        encoding="utf-8"
    )
    return out_dir
